
# Generated by Django 4.2.13 on 2024-05-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("stablish_time", models.DateField()),
                ("ceo", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="BrandDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headquarters", models.CharField(max_length=256)),
                ("founder", models.CharField(max_length=256)),
                ("market_ocp", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GPU_name", models.CharField(max_length=256)),
                ("type", models.CharField(max_length=256)),
                ("frequency", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "power_dissipation",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("VRAM_cap", models.DecimalField(decimal_places=2, max_digits=5)),
                ("VRAM_type", models.DecimalField(decimal_places=2, max_digits=5)),
                ("publish_time", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "Brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.brand"
                    ),
                ),
                (
                    "GPU",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.gpu"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="brand_detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="data.branddetail"
            ),
        ),
    ]
