
# Generated by Django 4.2.13 on 2024-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpu",
            name="VRAM_type",
            field=models.CharField(max_length=256),
        ),
    ]
