# Generated by Django 4.2.13 on 2024-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_alter_branddetail_market_ocp_alter_gpu_vram_cap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=256)),
                ("account_number", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name="price",
            name="price",
        ),
    ]
