# Generated by Django 4.2.13 on 2024-06-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_user_remove_price_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="Price",
            field=models.DecimalField(decimal_places=2, default=14999.0, max_digits=10),
            preserve_default=False,
        ),
    ]
